---
apiVersion: v1
data:
  extra: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjek5USTNOREU0Tml3aWFXRjBJam94TnpNMU1qYzBNVGcyZlEuNjRfYlNwNHJ3Ui1oYTRGWENTRHVRY3VyU24xNUZEWHFjd3JxTGpzRzNsZw==
kind: Secret
metadata:
  name: chat-app-secret
type: Opaque